# Generated by Django 4.1.3 on 2022-11-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_siteusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteusers',
            name='password',
        ),
    ]
