# Generated by Django 4.1.3 on 2022-11-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(default='hello'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
