# Generated by Django 4.1.3 on 2022-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_image_caption_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
