# Generated by Django 4.1.3 on 2022-11-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_siteusers_picture'),
        ('myapp', '0009_alter_image_caption_alter_image_title_and_more'),
    ]

    operations = [
    ]
