# Generated by Django 4.1.3 on 2022-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20221123_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='picture',
            field=models.URLField(default='https://i.pinimg.com/736x/dd/f0/11/ddf0110aa19f445687b737679eec9cb2.jpg', max_length=255),
        ),
    ]
