# Generated by Django 4.1.3 on 2022-12-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_image_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
