# Generated by Django 4.1.3 on 2023-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_profile_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userProfileImg',
            field=models.ImageField(default='blankpfp.jpg', upload_to='profile_images'),
        ),
    ]
