# Generated by Django 4.1.3 on 2023-01-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_profile_userprofileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteusers',
            old_name='name',
            new_name='user',
        ),
    ]
