# Generated by Django 4.1.3 on 2023-01-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_name_siteusers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteusers',
            old_name='user',
            new_name='name',
        ),
    ]
