# Generated by Django 4.1.3 on 2023-01-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_user_siteusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userProfileImg',
            field=models.URLField(default='https://i.pinimg.com/736x/dd/f0/11/ddf0110aa19f445687b737679eec9cb2.jpg', max_length=255),
        ),
    ]
