# Generated by Django 4.1.3 on 2023-01-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_profile_userprofileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userProfileImg',
            field=models.ImageField(blank=True, default='/images/blankpfp.jpg', null=True, upload_to=''),
        ),
    ]
