# Generated by Django 4.1.3 on 2023-03-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_image_userwhoposted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jadenSite',
        ),
        migrations.DeleteModel(
            name='SiteUsers',
        ),
    ]
