# Generated by Django 4.1.3 on 2023-03-24 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='postedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
